#!/bin/sh

if [ ! -f "./gradlew" ] || [ ! -x "./gradlew" ]; then
    echo "Error: ./gradlew not found or not executable."
    echo "Please ensure the project is properly set up."
    exit 1
fi

echo "Running KtLint..."
./gradlew app:ktlintCheck --no-daemon -p .
if [ $? -ne 0 ]; then
    echo "KtLint failed. Push aborted."
    exit 1
fi
